import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Nav from "../components/Nav";
import Image from "next/image";

const Home: NextPage = () => {
  const [menuHover, setMenuHover] = useState(false);

  return (
    <div className="flex justify-start max-w-[2440px]  mx-auto relative flex-col-reverse md:flex-row">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Nav menuHover={menuHover} setMenuHover={setMenuHover} />
        <div className="flex w-full h-screen">
          <div
            className={`max-w-[800px] w-full bg-opv-pink-500 transition duration-500 ease-in-out ${
              menuHover ? "translate-x-[10rem]" : "translate-x-[-4rem]"
            } [clip-path:polygon(0_0,65%_0,100%_100%,0%_100%)] z-20`}
          >
            <Image
              className="bg-opv-pink-500 opacity-40 "
              src="/bg-3.png"
              layout="fill"
              objectPosition="top"
              objectFit="cover"
              alt="OPV"
            />
          </div>
        </div>
        <div className="relative top-14 right-12  w-full max-h-[82px] max-w-[300px] md:max-h-[157px] md:max-w-[571px]">
          <Image src="/logo-opv.jpeg" layout="fill" alt="OPV" />

          <div className="relative mt-10">
            <div className="absolute top-40 left-[260px]">
              <Image
                src="https://images.rawpixel.com/image_1000/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvNDM3LWZlbGl4LTE1OF8xLmpwZw.jpg"
                width="300"
                height="300"
                alt="show"
                className="rounded-full animate-[firewoks_10s_ease-in-out_infinite]"
              />
            </div>

            <div className="absolute top-[156px] left-0">
              <Image
                src="https://images.rawpixel.com/image_1000/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvNDM3LWZlbGl4LTE1NS5qcGc.jpg"
                width="150"
                height="150"
                alt="show"
                className="rounded-full animate-[firewoks_10s_ease-in-out_1.5s_infinite]"
              />
            </div>

            <div className="absolute top-[460px] left-[60px]">
              <Image
                src="https://images.rawpixel.com/image_1000/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvdXB3azYyMTk1ODI5LXdpa2ltZWRpYS1pbWFnZS1rb3dzNmcxZi5qcGc.jpg"
                width="200"
                height="200"
                alt="show"
                className="rounded-full animate-[firewoks_10s_ease-in-out_3s_infinite]"
              />
            </div>
          </div>
        </div>
      </>
    </div>
  );
};

export default Home;
